import JSZip from "jszip";
import type { EditorState } from "./store";
import type { CBlock } from "./_types";
import { buildJavaModEventHandler } from "../../lib/codegenJava";

/* ═══════════════════════════════════════════
   悪用防止の注意喚起（生成物に必ず同梱）
   このアプリで作ったものが悪用されないため。
   ═══════════════════════════════════════════ */
const NOTICE_TEXT = [
  "================================================================",
  "  利用上の注意 / IMPORTANT — Responsible Use",
  "================================================================",
  "このアドオン/Mod は CUBICENGINE で生成されました。",
  "",
  "【日本語】",
  "・利用は自己責任で行ってください。",
  "・自分が管理するワールド、または明確に許可を得たサーバーでのみ使用してください。",
  "・他者への迷惑行為（グリーフ・チート・ハラスメント・サーバー妨害等）を目的とした",
  "  利用を禁止します。",
  "・本ツールおよび作者・運営は、生成物の内容、および生成物の使用によって生じた",
  "  いかなる損害・トラブルについても責任を負いません。",
  "・本ツールおよび生成物は非公式です。Mojang Studios・Microsoft とは一切関係がなく、",
  "  承認・提携を受けていません。Minecraft は Mojang Studios の商標です。",
  "",
  "[English]",
  "- Use at your own risk and responsibility.",
  "- Use only on worlds you own, or servers where you have explicit permission.",
  "- Malicious use (griefing, cheating, harassment, disrupting servers, etc.) is",
  "  strictly prohibited.",
  "- The tool, its authors and operators accept no liability for the content of,",
  "  or any damage arising from, the generated output.",
  "- NOT an official Minecraft product. Not approved by or associated with Mojang",
  "  or Microsoft. \"Minecraft\" is a trademark of Mojang Studios.",
  "",
  "Generated by CUBICENGINE.",
  "================================================================",
].join("\n");

/** コード先頭に入れる短い注意コメント（// 形式：JS/Java 共通） */
const NOTICE_COMMENT = [
  "// 利用上の注意 / Responsible Use —",
  "//   利用は自己責任で。自分が管理する、または許可を得たワールド/サーバーでのみ使用可。",
  "//   グリーフ・チート・嫌がらせ等の不正/迷惑利用は禁止。作者・運営は一切の責任を負いません。",
  "//   非公式ツール。Mojang Studios / Microsoft とは無関係。Minecraft は Mojang Studios の商標。",
  "//   Not affiliated with Mojang or Microsoft. Generated by CUBICENGINE.",
].join("\n");

/** store.logicGraphJson から積み木グラフ(CBlock[])を復元（壊れていたら空配列） */
function parseLogicBlocks(json: string): CBlock[] {
  try {
    const data = JSON.parse(json || "{}");
    return Array.isArray(data?.blocks) ? (data.blocks as CBlock[]) : [];
  } catch {
    return [];
  }
}

/* ═══════════════════════════════════════════
   Security Sanitizers
   ═══════════════════════════════════════════ */

function escJs(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\0/g, "\\0");
}

function escJava(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

function escToml(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

function escComment(s: string): string {
  return s.replace(/[\n\r]/g, " ");
}

function sanitizeMcId(s: string): string {
  return s.replace(/[^a-z0-9_-]/g, "");
}

function sanitizeSlug(s: string): string {
  const slug = s.replace(/\s+/g, "_").replace(/[^a-z0-9_-]/gi, "").toLowerCase();
  return slug || "project";
}

function sanitizeClassName(s: string): string {
  const cls = s.replace(/\s+/g, "").replace(/[^a-zA-Z0-9]/g, "");
  const safe = /^\d/.test(cls) ? `Mod${cls}` : cls;
  return safe || "Mod";
}

function sanitizeModId(s: string): string {
  const id = s.replace(/[^a-z0-9_]/g, "");
  return id || "mod";
}

function sanitizeBlockName(s: string): string {
  return sanitizeMcId(s) || "block";
}

/* ═══════════════════════════════════════════
   UUID Generator
   ═══════════════════════════════════════════ */
function uuid(): string {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/* ═══════════════════════════════════════════
   Download Helper
   ═══════════════════════════════════════════ */
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/* ═══════════════════════════════════════════
   Colored Texture (16x16 PNG — per-pixel hue variation)
   ═══════════════════════════════════════════ */
function createColoredTexture(hexColor: string): Promise<Uint8Array> {
  return new Promise((resolve) => {
    const canvas = document.createElement("canvas");
    canvas.width = 16;
    canvas.height = 16;
    const ctx = canvas.getContext("2d")!;

    const r = parseInt(hexColor.slice(1, 3), 16) || 0;
    const g = parseInt(hexColor.slice(3, 5), 16) || 0;
    const b = parseInt(hexColor.slice(5, 7), 16) || 0;

    // Minecraft-style: each pixel shifts brightness slightly
    for (let x = 0; x < 16; x++) {
      for (let y = 0; y < 16; y++) {
        const d = (Math.random() - 0.5) * 40;
        const pr = Math.min(255, Math.max(0, Math.round(r + d)));
        const pg = Math.min(255, Math.max(0, Math.round(g + d)));
        const pb = Math.min(255, Math.max(0, Math.round(b + d)));
        ctx.fillStyle = `rgb(${pr},${pg},${pb})`;
        ctx.fillRect(x, y, 1, 1);
      }
    }

    canvas.toBlob(
      (blob) => blob!.arrayBuffer().then((buf) => resolve(new Uint8Array(buf))),
      "image/png",
    );
  });
}

/* ═══════════════════════════════════════════
   Placeholder Icon (1×1 purple PNG)
   ═══════════════════════════════════════════ */
function createPlaceholderIcon(): Uint8Array {
  return new Uint8Array([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
    0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
    0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53,
    0xde, 0x00, 0x00, 0x00, 0x0c, 0x49, 0x44, 0x41,
    0x54, 0x08, 0xd7, 0x63, 0xd8, 0xac, 0xd9, 0x06,
    0x00, 0x01, 0x01, 0x00, 0x85, 0x4e, 0xf7, 0x27,
    0x23, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e,
    0x44, 0xae, 0x42, 0x60, 0x82,
  ]);
}

/* ═══════════════════════════════════════════
   Bedrock Addon Export
   Formats:
     mcaddon → BP + RP bundled in one zip
     mcpack  → BP-only .mcpack + RP-only .mcpack (two downloads)
     zip     → same as mcaddon but .zip extension
   ═══════════════════════════════════════════ */
/** data URL → Uint8Array（カスタムアイコン用） */
async function dataUrlToBytes(dataUrl: string): Promise<Uint8Array> {
  const res = await fetch(dataUrl);
  return new Uint8Array(await res.arrayBuffer());
}

export async function exportBedrock(state: EditorState, jsCode: string) {
  const name = sanitizeSlug(state.projectName);
  const desc = `${escComment(state.projectName)} — Generated by CUBICENGINE`;
  const compression = (state.compress ? "DEFLATE" : "STORE") as "DEFLATE" | "STORE";
  const compressionOptions = state.compress ? { level: 6 } : undefined;

  const bpUuid = uuid();
  const rpUuid = uuid();
  const bpModuleUuid = uuid();
  const rpModuleUuid = uuid();

  // アイコン: カスタム画像があればそれを使う、なければデフォルト
  const iconBytes = state.packIconDataUrl
    ? await dataUrlToBytes(state.packIconDataUrl)
    : createPlaceholderIcon();

  /* ── Build Behavior Pack folder contents ── */
  async function fillBP(bp: JSZip) {
    bp.file(
      "manifest.json",
      JSON.stringify(
        {
          format_version: 2,
          header: {
            name: `${state.projectName} BP`,
            description: desc,
            uuid: bpUuid,
            version: [1, 0, 0],
            // 1.20.10 以降ならどのバージョンでもロード可能
          min_engine_version: [1, 20, 10],
          },
          modules: [
            {
              type: "script",
              language: "javascript",
              uuid: bpModuleUuid,
              entry: "scripts/main.js",
              version: [1, 0, 0],
            },
          ],
          dependencies: [
            // ベータAPI ON=実験的スクリプトAPI(-beta / ワールドの「ベータAPI」実験が必要)
            // OFF=安定版(1.6.0 / Minecraft 1.20.30 以降・実験的機能不要)
            { module_name: "@minecraft/server", version: state.betaApi ? "1.6.0-beta" : "1.6.0" },
            // @minecraft/server-ui は使用時のみ追加（常時追加するとロード失敗の原因になる）
            ...(jsCode.includes("ActionFormData") || jsCode.includes("ModalFormData") || jsCode.includes("MessageFormData")
              ? [{ module_name: "@minecraft/server-ui", version: state.betaApi ? "1.1.0-beta" : "1.1.0" }]
              : []),
            { uuid: rpUuid, version: [1, 0, 0] },
          ],
          // capabilities は不要（script_eval 等の非公式フラグはロードを妨げる）
        },
        null,
        2,
      ),
    );

    // ★ jsCode はすでに import 文・console.warn ログを含むので二重追加しない
    const mainJsBody = jsCode.trim()
      ? jsCode
      : [
          `// ${escComment(state.projectName)} — CUBICENGINE`,
          `// Generated: ${new Date().toISOString()}`,
          ``,
          `import { world, system } from "@minecraft/server";`,
          ``,
          `console.warn("[${escJs(state.projectName)}] ロジックブロックが空です");`,
        ].join("\n");
    bp.file("scripts/main.js", NOTICE_COMMENT + "\n\n" + mainJsBody);

    // 悪用防止の注意喚起を同梱
    bp.file("NOTICE.txt", NOTICE_TEXT);

    bp.file("pack_icon.png", iconBytes);

    for (const block of state.blocks) {
      const components: Record<string, unknown> = {
        // unit_cube = 標準の1×1×1キューブ（カスタムジオメトリ不要）
        "minecraft:unit_cube": {},
        "minecraft:material_instances": {
          "*": { texture: `cubicengine_${block.name}`, render_method: "opaque" },
        },
      };
      // 本格モード(registered)のブロックは設定を反映
      if (block.registered) {
        if (typeof block.hardness === "number") {
          components["minecraft:destructible_by_mining"] = { seconds_to_destroy: Math.max(0, block.hardness) };
        }
        if (block.lightLevel && block.lightLevel > 0) {
          components["minecraft:light_emission"] = Math.min(15, Math.max(0, Math.round(block.lightLevel)));
        }
      }
      bp.file(
        `blocks/${block.name}.json`,
        JSON.stringify(
          {
            format_version: "1.20.10",
            "minecraft:block": {
              description: {
                identifier: `cubicengine:${block.name}`,
                menu_category: { category: "construction" },
              },
              components,
            },
          },
          null,
          2,
        ),
      );
    }
  }

  /* ── Build Resource Pack folder contents ── */
  async function fillRP(rp: JSZip) {
    rp.file(
      "manifest.json",
      JSON.stringify(
        {
          format_version: 2,
          header: {
            name: `${state.projectName} RP`,
            description: desc,
            uuid: rpUuid,
            version: [1, 0, 0],
            min_engine_version: [1, 20, 10],
          },
          modules: [{ type: "resources", uuid: rpModuleUuid, version: [1, 0, 0] }],
        },
        null,
        2,
      ),
    );

    rp.file("pack_icon.png", iconBytes);

    const textureData: Record<string, { textures: string }> = {};
    const blocksJson: Record<string, { textures: string; sound: string }> = {};
    for (const block of state.blocks) {
      textureData[`cubicengine_${block.name}`] = { textures: `textures/blocks/${block.name}` };
      blocksJson[`cubicengine:${block.name}`] = { textures: `cubicengine_${block.name}`, sound: "stone" };
    }

    rp.file(
      "textures/terrain_texture.json",
      JSON.stringify(
        {
          resource_pack_name: state.projectName,
          texture_name: "atlas.terrain",
          padding: 8,
          num_mip_levels: 4,
          texture_data: textureData,
        },
        null,
        2,
      ),
    );
    rp.file("blocks.json", JSON.stringify(blocksJson, null, 2));

    // 表示名(lang): 本格ブロックは displayName を、それ以外はブロック名をゲーム内名に
    const langLines = state.blocks
      .map((b) => `tile.cubicengine:${b.name}.name=${(b.registered && b.displayName) ? b.displayName : b.name}`)
      .join("\n");
    rp.file("texts/en_US.lang", langLines + "\n");
    rp.file("texts/languages.json", JSON.stringify(["en_US"], null, 2));

    for (const block of state.blocks) {
      const tex = await createColoredTexture(block.faces.top.color);
      rp.file(`textures/blocks/${block.name}.png`, tex);
    }

    // カスタムジオメトリは不要（unit_cube を使用するため）
  }

  const genOpts = { type: "blob" as const, compression, compressionOptions };

  if (state.exportFormat === "mcpack") {
    // Export Behavior Pack and Resource Pack as separate .mcpack files
    const bpZip = new JSZip();
    await fillBP(bpZip);
    const bpBlob = await bpZip.generateAsync(genOpts);
    downloadBlob(bpBlob, `${name}_BP.mcpack`);

    const rpZip = new JSZip();
    await fillRP(rpZip);
    const rpBlob = await rpZip.generateAsync(genOpts);
    downloadBlob(rpBlob, `${name}_RP.mcpack`);
  } else {
    // mcaddon or zip: bundle both packs together
    const zip = new JSZip();
    const bp = zip.folder(`${name}_BP`)!;
    const rp = zip.folder(`${name}_RP`)!;
    await fillBP(bp);
    await fillRP(rp);

    const ext = state.exportFormat === "zip" ? ".zip" : ".mcaddon";
    const blob = await zip.generateAsync(genOpts);
    downloadBlob(blob, `${name}${ext}`);
  }

  return true;
}

/* ═══════════════════════════════════════════
   Java Edition Export (Forge 1.20.1-47.3.0)
   ═══════════════════════════════════════════ */
export async function exportJava(state: EditorState, jsCode: string) {
  const zip = new JSZip();
  const name = sanitizeSlug(state.projectName);
  const className = sanitizeClassName(state.projectName);
  const modId = sanitizeModId(name);
  const pkg = `com.cubicengine.${modId}`;
  const pkgPath = `com/cubicengine/${modId}`;
  const compression = (state.compress ? "DEFLATE" : "STORE") as "DEFLATE" | "STORE";
  const compressionOptions = state.compress ? { level: 6 } : undefined;

  // ─── build.gradle ───
  zip.file(
    "build.gradle",
    [
      `plugins {`,
      `    id 'net.minecraftforge.gradle' version '6.0.+'`,
      `}`,
      ``,
      `version = '1.0.0'`,
      `group = '${pkg}'`,
      `archivesBaseName = '${modId}'`,
      ``,
      `java.toolchain.languageVersion = JavaLanguageVersion.of(17)`,
      ``,
      `minecraft {`,
      `    mappings channel: 'official', version: '1.20.1'`,
      `    runs {`,
      `        client { workingDirectory project.file('run') }`,
      `        server { workingDirectory project.file('run') }`,
      `    }`,
      `}`,
      ``,
      `dependencies {`,
      `    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'`,
      `}`,
    ].join("\n"),
  );

  // ─── gradle.properties ───
  zip.file(
    "gradle.properties",
    [
      `org.gradle.jvmargs=-Xmx3G`,
      `org.gradle.daemon=false`,
    ].join("\n"),
  );

  // ─── settings.gradle ───
  zip.file(
    "settings.gradle",
    [
      `pluginManagement {`,
      `    repositories {`,
      `        gradlePluginPortal()`,
      `        maven { url = 'https://maven.minecraftforge.net/' }`,
      `    }`,
      `}`,
      `rootProject.name = '${modId}'`,
    ].join("\n"),
  );

  // ─── Gradle Wrapper（本物・Forge 1.20.1 MDK 由来 / Gradle 8.8）───
  // これを同梱することで、ユーザーは JDK17 だけで `./gradlew build` 一発で通る。
  // ※P1.5/P1.6(2026-07-01)で final jar まで実ビルド検証済み。バイナリ(jar)や改行を壊さぬよう base64 で格納。
  // 99KB あるため、Java出力時のみ動的importで読み込む（Bedrock利用者のバンドルを太らせない）。
  const {
    GRADLEW_SH_B64,
    GRADLEW_BAT_B64,
    GRADLE_WRAPPER_JAR_B64,
    GRADLE_WRAPPER_PROPERTIES_B64,
  } = await import("../../lib/gradleWrapper");
  zip.file("gradle/wrapper/gradle-wrapper.properties", GRADLE_WRAPPER_PROPERTIES_B64, { base64: true });
  zip.file("gradle/wrapper/gradle-wrapper.jar", GRADLE_WRAPPER_JAR_B64, { base64: true });
  zip.file("gradlew", GRADLEW_SH_B64, { base64: true, unixPermissions: 0o755 });
  zip.file("gradlew.bat", GRADLEW_BAT_B64, { base64: true });

  // ─── Main Mod Class ───
  const src = zip.folder(`src/main/java/${pkgPath}`)!;

  src.file(
    `${className}Mod.java`,
    [
      `package ${pkg};`,
      ``,
      `import net.minecraftforge.common.MinecraftForge;`,
      `import net.minecraftforge.fml.common.Mod;`,
      `import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;`,
      `import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;`,
      `import org.apache.logging.log4j.LogManager;`,
      `import org.apache.logging.log4j.Logger;`,
      ``,
      `@Mod("${modId}")`,
      `public class ${className}Mod {`,
      `    public static final String MOD_ID = "${modId}";`,
      `    private static final Logger LOGGER = LogManager.getLogger();`,
      ``,
      `    public ${className}Mod() {`,
      `        var bus = FMLJavaModLoadingContext.get().getModEventBus();`,
      `        bus.addListener(this::setup);`,
      `        ModBlocks.register(bus);`,
      `        ModItems.register(bus);`,
      `        MinecraftForge.EVENT_BUS.register(this);`,
      `        LOGGER.info("[${escJava(state.projectName)}] Mod initialized!");`,
      `    }`,
      ``,
      `    private void setup(final FMLCommonSetupEvent event) {`,
      `        LOGGER.info("[${escJava(state.projectName)}] Setup complete!");`,
      `    }`,
      `}`,
    ].join("\n"),
  );

  // ─── Block Registration ───
  src.file(
    "ModBlocks.java",
    [
      `package ${pkg};`,
      ``,
      `import net.minecraft.world.level.block.Block;`,
      `import net.minecraft.world.level.block.state.BlockBehaviour;`,
      `import net.minecraftforge.registries.DeferredRegister;`,
      `import net.minecraftforge.registries.ForgeRegistries;`,
      `import net.minecraftforge.registries.RegistryObject;`,
      `import net.minecraftforge.eventbus.api.IEventBus;`,
      ``,
      `public class ModBlocks {`,
      `    public static final DeferredRegister<Block> BLOCKS =`,
      `        DeferredRegister.create(ForgeRegistries.BLOCKS, ${className}Mod.MOD_ID);`,
      ``,
      ...state.blocks.map((b) => {
        const bn = sanitizeBlockName(b.name);
        return [
          `    public static final RegistryObject<Block> ${bn.toUpperCase()} =`,
          `        BLOCKS.register("${escJava(bn)}",`,
          `            () -> new Block(BlockBehaviour.Properties.of()`,
          `                .strength(3.0f).requiresCorrectToolForDrops()));`,
        ].join("\n");
      }),
      ``,
      `    public static void register(IEventBus bus) {`,
      `        BLOCKS.register(bus);`,
      `    }`,
      `}`,
    ].join("\n"),
  );

  // ─── Item Registration ───
  src.file(
    "ModItems.java",
    [
      `package ${pkg};`,
      ``,
      `import net.minecraft.world.item.BlockItem;`,
      `import net.minecraft.world.item.Item;`,
      `import net.minecraftforge.registries.DeferredRegister;`,
      `import net.minecraftforge.registries.ForgeRegistries;`,
      `import net.minecraftforge.registries.RegistryObject;`,
      `import net.minecraftforge.eventbus.api.IEventBus;`,
      ``,
      `public class ModItems {`,
      `    public static final DeferredRegister<Item> ITEMS =`,
      `        DeferredRegister.create(ForgeRegistries.ITEMS, ${className}Mod.MOD_ID);`,
      ``,
      ...state.blocks.map((b) => {
        const bn = sanitizeBlockName(b.name);
        return [
          `    public static final RegistryObject<Item> ${bn.toUpperCase()}_ITEM =`,
          `        ITEMS.register("${escJava(bn)}",`,
          `            () -> new BlockItem(ModBlocks.${bn.toUpperCase()}.get(),`,
          `                new Item.Properties()));`,
        ].join("\n");
      }),
      ``,
      `    public static void register(IEventBus bus) {`,
      `        ITEMS.register(bus);`,
      `    }`,
      `}`,
    ].join("\n"),
  );

  // ─── Event Handler (積み木グラフ → 実 Java ロジック) ───
  // ★ 旧版は Bedrock用JSをコメント化するだけで何も動かなかった。
  //   logicGraphJson から CBlock[] を復元し、codegenJava で本物の
  //   @SubscribeEvent ハンドラを生成する。
  const logicBlocks = parseLogicBlocks(state.logicGraphJson);
  src.file(
    "ModEventHandler.java",
    NOTICE_COMMENT + "\n" + buildJavaModEventHandler(logicBlocks, {
      pkg,
      className,
      projectName: state.projectName,
    }),
  );

  // ─── mods.toml ───
  const resources = zip.folder("src/main/resources")!;
  const metaInf = resources.folder("META-INF")!;

  metaInf.file(
    "mods.toml",
    [
      `modLoader="javafml"`,
      `loaderVersion="[47,)"`,
      `license="MIT"`,
      ``,
      `[[mods]]`,
      `modId="${modId}"`,
      `version="1.0.0"`,
      `displayName="${escToml(state.projectName)}"`,
      `description='''${escComment(state.projectName)} — Generated by CUBICENGINE'''`,
      ``,
      `[[dependencies.${modId}]]`,
      `    modId="forge"`,
      `    mandatory=true`,
      `    versionRange="[47,)"`,
      `    ordering="NONE"`,
      `    side="BOTH"`,
      ``,
      `[[dependencies.${modId}]]`,
      `    modId="minecraft"`,
      `    mandatory=true`,
      `    versionRange="[1.20.1,1.21)"`,
      `    ordering="NONE"`,
      `    side="BOTH"`,
    ].join("\n"),
  );

  // pack.mcmeta
  resources.file(
    "pack.mcmeta",
    JSON.stringify({ pack: { description: `${state.projectName} Resources`, pack_format: 15 } }, null, 2),
  );

  // Block models, blockstates, item models, textures, lang
  const langEntries: Record<string, string> = {};
  for (const block of state.blocks) {
    resources.file(
      `assets/${modId}/blockstates/${block.name}.json`,
      JSON.stringify({ variants: { "": { model: `${modId}:block/${block.name}` } } }, null, 2),
    );
    resources.file(
      `assets/${modId}/models/block/${block.name}.json`,
      JSON.stringify({ parent: "block/cube_all", textures: { all: `${modId}:block/${block.name}` } }, null, 2),
    );
    resources.file(
      `assets/${modId}/models/item/${block.name}.json`,
      JSON.stringify({ parent: `${modId}:block/${block.name}` }, null, 2),
    );
    const tex = await createColoredTexture(block.faces.top.color);
    resources.file(`assets/${modId}/textures/block/${block.name}.png`, tex);

    langEntries[`block.${modId}.${block.name}`] = block.name
      .replace(/_/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase());
  }
  resources.file(`assets/${modId}/lang/en_us.json`, JSON.stringify(langEntries, null, 2));

  // README
  zip.file(
    "README.md",
    [
      `# ${state.projectName}`,
      ``,
      `Generated by **CUBICENGINE** on ${new Date().toLocaleDateString("ja-JP")}`,
      ``,
      `## ⚠️ 利用上の注意 / Responsible Use`,
      ``,
      "```",
      NOTICE_TEXT,
      "```",
      ``,
      `## ビルド方法 / Setup`,
      `必要なのは **JDK 17** だけです（Gradleラッパーは同梱済み）。`,
      ``,
      `1. **JDK 17** をインストール（例: https://adoptium.net/ ）`,
      `2. このフォルダで次を実行（初回は Gradle と Minecraft/Forge を自動DL）:`,
      `   - Windows: \`gradlew.bat build\``,
      `   - Mac / Linux: \`./gradlew build\``,
      `3. できあがった \`build/libs/${modId}-1.0.0.jar\` を、`,
      `   Forge 1.20.1 を導入した Minecraft の \`mods/\` フォルダに入れる`,
      `4. Minecraft（Forge 1.20.1）を起動すれば Mod が読み込まれます`,
      ``,
      `## Blocks`,
      ...state.blocks.map((b) => `- \`${b.name}\``),
    ].join("\n"),
  );

  // 悪用防止の注意喚起を同梱
  zip.file("NOTICE.txt", NOTICE_TEXT);

  const blob = await zip.generateAsync({
    type: "blob",
    compression,
    compressionOptions,
  });
  downloadBlob(blob, `${name}-forge-mod.zip`);
  return true;
}

/* ═══════════════════════════════════════════
   Main Export Dispatcher
   ═══════════════════════════════════════════ */
export async function exportProject(state: EditorState, jsCode: string): Promise<boolean> {
  if (state.targetPlatform === "bedrock") {
    return exportBedrock(state, jsCode);
  } else {
    return exportJava(state, jsCode);
  }
}
