// 利用上の注意 / Responsible Use —
//   利用は自己責任で。自分が管理する、または許可を得たワールド/サーバーでのみ使用可。
//   グリーフ・チート・嫌がらせ等の不正/迷惑利用は禁止。作者・運営は一切の責任を負いません。
//   非公式ツール。Mojang Studios / Microsoft とは無関係。Minecraft は Mojang Studios の商標。
//   Not affiliated with Mojang or Microsoft. Generated by CUBICENGINE.
package com.cubicengine.cubicengine_generic;

// ============================================================
//  CUBICENGINE Studio — 自動生成コード (GROVE / Java)
//  Forge 1.20.1 (47.x) / Java 17
//  このファイルは積み木グラフから生成されています。
// ============================================================

import com.google.gson.JsonObject;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.ai.attributes.AttributeInstance;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.ServerChatEvent;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.event.entity.EntityJoinLevelEvent;
import net.minecraftforge.event.entity.living.LivingDropsEvent;
import net.minecraftforge.event.entity.living.LivingHurtEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.event.entity.player.PlayerInteractEvent;
import net.minecraftforge.event.level.BlockEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;

@Mod.EventBusSubscriber(modid = cubicenginegenericMod.MOD_ID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class ModEventHandler {

    @SubscribeEvent
    public static void onPlayerJoin(PlayerEvent.PlayerLoggedInEvent event) {
        if (event.getEntity() instanceof ServerPlayer player) {
            // Version Check Warning
            if (DynamicRegistry.modData != null && DynamicRegistry.modData.has("spec")) {
                int spec = DynamicRegistry.modData.get("spec").getAsInt();
                if (spec != 3) {
                    player.sendSystemMessage(Component.literal("§c[CUBICENGINE] 警告: SPEC_VERSION が一致しません。MODが正常に動かない可能性があります。Webからエクスポートし直してください。"));
                }
            }
            LogicInterpreter.onTrigger("join", player, null);
        }
    }

    @SubscribeEvent
    public static void onPlayerTick(TickEvent.PlayerTickEvent event) {
        if (event.phase == TickEvent.Phase.END && event.player instanceof ServerPlayer player) {
            // To prevent lag, you might want to execute this less frequently, but for now we execute every tick.
            LogicInterpreter.onTrigger("tick", player, null);
        }
    }

    @SubscribeEvent
    public static void onEntityJoin(EntityJoinLevelEvent event) {
        if (event.getEntity() instanceof LivingEntity living && !event.getLevel().isClientSide()) {
            CompoundTag tag = living.getPersistentData();
            if (tag.contains("CubicMobId") && tag.getBoolean("CubicMobNeedsInit")) {
                String mobId = tag.getString("CubicMobId");
                JsonObject mobJson = DynamicRegistry.MOBS_MAP.get(mobId);
                
                if (mobJson != null) {
                    // Update Name
                    if (mobJson.has("displayName")) {
                        living.setCustomName(Component.literal(mobJson.get("displayName").getAsString()));
                        living.setCustomNameVisible(true);
                    }
                    
                    // Update Health
                    if (mobJson.has("health")) {
                        AttributeInstance healthAttr = living.getAttribute(Attributes.MAX_HEALTH);
                        if (healthAttr != null) {
                            healthAttr.setBaseValue(mobJson.get("health").getAsDouble());
                            living.setHealth((float) mobJson.get("health").getAsDouble());
                        }
                    }
                    
                    // Update Attack Damage
                    if (mobJson.has("attackDamage")) {
                        AttributeInstance attackAttr = living.getAttribute(Attributes.ATTACK_DAMAGE);
                        if (attackAttr != null) {
                            attackAttr.setBaseValue(mobJson.get("attackDamage").getAsDouble());
                        }
                    }
                    
                    // Update Movement Speed
                    if (mobJson.has("movementSpeed")) {
                        AttributeInstance speedAttr = living.getAttribute(Attributes.MOVEMENT_SPEED);
                        if (speedAttr != null) {
                            speedAttr.setBaseValue(mobJson.get("movementSpeed").getAsDouble());
                        }
                    }
                }
                
                // Clear the init flag so we don't apply base values again when the entity is loaded from disk
                tag.putBoolean("CubicMobNeedsInit", false);
            }
        }
    }

    @SubscribeEvent
    public static void onLivingDrops(LivingDropsEvent event) {
        LivingEntity living = event.getEntity();
        if (living.level().isClientSide()) return;
        
        CompoundTag tag = living.getPersistentData();
        if (tag.contains("CubicMobId")) {
            String mobId = tag.getString("CubicMobId");
            JsonObject mobJson = DynamicRegistry.MOBS_MAP.get(mobId);
            
            if (mobJson != null && mobJson.has("drops")) {
                // Clear vanilla drops
                event.getDrops().clear();
                
                // Add custom drops
                com.google.gson.JsonArray drops = mobJson.getAsJsonArray("drops");
                for (com.google.gson.JsonElement e : drops) {
                    JsonObject drop = e.getAsJsonObject();
                    String itemStr = drop.get("item").getAsString();
                    int min = drop.get("min").getAsInt();
                    int max = drop.get("max").getAsInt();
                    
                    int count = min + living.getRandom().nextInt(Math.max(1, max - min + 1));
                    if (count > 0) {
                        net.minecraft.world.item.Item item = ForgeRegistries.ITEMS.getValue(new ResourceLocation(itemStr));
                        if (item != null && item != net.minecraft.world.item.Items.AIR) {
                            ItemStack stack = new ItemStack(item, count);
                            event.getDrops().add(new ItemEntity(living.level(), living.getX(), living.getY(), living.getZ(), stack));
                        }
                    }
                }
            }
        }
    }

    @SubscribeEvent
    public static void onBlockBreak(BlockEvent.BreakEvent event) {
        if (event.getPlayer() instanceof ServerPlayer player) {
            JsonObject ctx = new JsonObject();
            ctx.addProperty("block", ForgeRegistries.BLOCKS.getKey(event.getState().getBlock()).toString());
            LogicInterpreter.onTrigger("break", player, ctx);
        }
    }

    @SubscribeEvent
    public static void onBlockPlace(BlockEvent.EntityPlaceEvent event) {
        if (event.getEntity() instanceof ServerPlayer player) {
            JsonObject ctx = new JsonObject();
            ctx.addProperty("block", ForgeRegistries.BLOCKS.getKey(event.getPlacedBlock().getBlock()).toString());
            LogicInterpreter.onTrigger("place", player, ctx);
        }
    }

    @SubscribeEvent
    public static void onRightClickItem(PlayerInteractEvent.RightClickItem event) {
        if (event.getEntity() instanceof ServerPlayer player) {
            JsonObject ctx = new JsonObject();
            ctx.addProperty("item", ForgeRegistries.ITEMS.getKey(event.getItemStack().getItem()).toString());
            LogicInterpreter.onTrigger("useItem", player, ctx);
        }
    }

    @SubscribeEvent
    public static void onRightClickBlock(PlayerInteractEvent.RightClickBlock event) {
        if (event.getEntity() instanceof ServerPlayer player) {
            JsonObject ctx = new JsonObject();
            ctx.addProperty("item", ForgeRegistries.ITEMS.getKey(event.getItemStack().getItem()).toString());
            LogicInterpreter.onTrigger("useItem", player, ctx);
        }
    }

    @SubscribeEvent
    public static void onHurt(LivingHurtEvent event) {
        if (event.getEntity() instanceof ServerPlayer player) {
            LogicInterpreter.onTrigger("hurt", player, null);
        }
    }

    @SubscribeEvent
    public static void onChat(ServerChatEvent event) {
        ServerPlayer player = event.getPlayer();
        if (player != null) {
            JsonObject ctx = new JsonObject();
            ctx.addProperty("message", event.getRawText());
            LogicInterpreter.onTrigger("chat", player, ctx);
        }
    }
}
